# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Fabrice'
on: [workflow_dispatch, push]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left nice_view_adapter nice_view","splitkb_aurora_corne_right nice_view_adapter nice_view"]'
